### ISSUE TITLE
google.api_core.exceptions.InternalServerError: 500 An internal error has occurred

### ISSUE THREAD

**Issue by Mebareksaf** [googleapis/python-certificate-manager#99]
#### Environment details

  - OS type and version: Google Cloud Function running in python 3.10.9 environment
  - Python version: 3.10.9
  - Packages: 
  * grpcio-status-1.51.1 
  * google-cloud-certificate-manager==1.2.0
  * google-api-core-2.11.0
  * googleapis-common-protos-1.57.0
  * functions-framework-3.0.0
  * cloudevents-1.2.0
  * setuptools-60.3.1
  * Flask-2.0.2

#### Steps to reproduce

  1. Create a Google Cloud Function in Python3.10 environment.
  2. Set Trigger type to Pub/Sub.
  3. Use a service account with Certificate-Manager-Owner Role granted to this service.
  4. Use these credentials within the Cloud Function.

#### Code example
**requirements.txt**
google-auth
google-cloud-certificate-manager
**main.py**
```python
import base64

from google.cloud import certificate_manager_v1
from google.oauth2 import service_account

from service_keys import service_accout as account


GS_CREDENTIALS = service_account.Credentials.from_service_account_info(account)

client = certificate_manager_v1.CertificateManagerClient(credentials=GS_CREDENTIALS)

def hello_pubsub(event, context):
    pubsub_message = base64.b64decode(event['data']).decode('utf-8')
    print(pubsub_message)
    
    get_map_entry = certificate_manager_v1.GetCertificateMapEntryRequest(
        name="projects/my-project/locations/global/certificateMaps/my-map-name/certificateMapsEntries/my-map-entry-name"
        )
    response = client.get_certificate_map_entry(request=get_map_entry)
    response = operation.result()
    print(response)
```

#### Stack trace
```
Traceback (most recent call last): File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/functions_framework/__init__.py", line 171, in view_func function(data, context) File "/workspace/main.py", line 93, in hello_pubsub response = client.get_certificate_map_entry(request=get_map_entry) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/cloud/certificate_manager_v1/services/certificate_manager/client.py", line 2059, in get_certificate_map_entry response = rpc( File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__ return wrapped_func(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in retry_wrapped_func return retry_target( File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target return target() File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/timeout.py", line 120, in func_with_timeout return func(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable raise exceptions.from_grpc_error(exc) from exc google.api_core.exceptions.InternalServerError: 500 An internal error has occurred (96f62157-00e0-43e3-afce-fcd5563c8d80) 
```

**Comment by parthea** [comment]
500 errors with `An internal error has occurred` indicates a problem on the backend. I'm going to close this as obsolete but please open a new issue if the issue re-appears so we can escalate to the API team.

**Comment by Mebareksaf** [comment]
> 500 errors with `An internal error has occurred` indicates a problem on the backend. I'm going to close this as obsolete but please open a new issue if the issue re-appears so we can escalate to the API team.

Hello, thank you for the reply!

I think this is an unhandled exception that happens at the API level, which causes the "get_map_entry" function to malfunction! And yes the error is always there.
